### ISSUE TITLE
[Question] My widget stopped working ?

### ISSUE THREAD

**Issue by celfred** [OpenBoard-org/OpenBoard#1123]
Hello,

I ahd a simple widget that I have been using from times to times  for many years now, and there now (since hen, I don't really know).

The widget is quite simple : once dropped on the board, it builds a table with a certain number of groups as rows and a certain number of challenges as columns. Each cell has a cross symbol, and once clicked, it turns into a tick and changes color.
See, nothing much…

But, I have 2 bugs with it now : 
1. If you click the 'Edit' button in the top right corner and then  open a select to change, for example, then number of groups, Openboard crashes. (It used to work fine and I haven't changed anything to my widget, so I have no idea what happened).
2.  The table works as expected (if you don't do #1 mentionned above ;) ) but if I quit OpenBoard and then come back, my widget is replaced with a grey box saying uncompatible widget. I have compared it to another widget of mine I have that works fine and I can't see any 'big' difference…

So if comeone can help me solve this issue (or at least point me into the right direction), I would greatly appreciate :) 

Here's my zipped widget.
[challenge.wgt.zip](https://github.com/user-attachments/files/17179698/challenge.wgt.zip)

 For information, I have OpenBoard running as a flatpak v.1.7.1 on Linux Mint 21.3.

Thanks !

**Comment by letsfindaway** [comment]
For 1., you most probably hit #1054, a Qt bug reported to the Qt team here: https://bugreports.qt.io/browse/QTBUG-128241. According to the bug report, it will be fixed in Qt 6.8.1. So currently you will either use an earlier Qt version or wait for 6.8.1.

For 2., I would like to see your JavaScript code. It might be that the compatibility check is wrong, but it might also be that there is some small incompatibility.

**Comment by letsfindaway** [comment]
For 2., it is the following piece of code from `index.html` at line 123:

```js
          window.widget.onleave = function () {
            exportData();
          };
```

`onleave` must now be handled differently. It is a signal, and you have to use it as described here in the Wiki: https://github.com/OpenBoard-org/OpenBoard/wiki/The-Web-Widgets-API#signals using the `connect()` function.

As far as I can see this is the only incompatibility.

**Comment by letsfindaway** [comment]
Wait, you also have to change the way how you read the preferences. The code starting with line 97 will no longer work, because functions are now asynchronous: https://github.com/OpenBoard-org/OpenBoard/wiki/The-Web-Widgets-API#functions

There are various ways to convert the code to asynchronous behavior. My suggestion would be to use `async` / `await` as in one of the examples. Note that `await` only works in a function declared as `async`!

**Comment by letsfindaway** [comment]
And BTW: do you know the "Web Inspector"? Right click on your application and open the Web Inspector. In the "Console" tab you will currently see the following error directly after startup:

```
Uncaught SyntaxError: Unexpected token 'o', "[object Promise]" is not valid JSON
    at JSON.parse (<anonymous>)
    at n.parseJSON (jquery-1.12.4.min.js:4:16646)
    at HTMLDocument.<anonymous> (index.html:108:31)
    at i (jquery-1.12.4.min.js:2:27449)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.min.js:2:28213)
    at Function.ready (jquery-1.12.4.min.js:2:30006)
    at HTMLDocument.K (jquery-1.12.4.min.js:2:30368)
```

This is because the simple call to `preference` now returns a `Promise` instead of the value.

The Web Inspector helps you to test and debug your applications. You can even set breakpoints and inspect the values of variables.

**Comment by letsfindaway** [comment]
> For information, I have OpenBoard running as a flatpak v.1.7.1 on Linux Mint 21.3.

The Flatpak used the Qt 6.7 version. The bug is contained in 6.9, 6.7.1 and 6.7.2 and is fixed in 6.7.3, which was released the day before yesterday. I do not know how long it takes that the Qt version hits the Flatpak runtime, but once it does, your issue 1. should be fixed. See https://bugreports.qt.io/browse/QTBUG-119908 (another issue for the same bug) and the very last line of the release notes https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.7.3/release-note.md.

KDE already switched to 6.7.3: https://github.com/KDE/flatpak-kde-runtime/tree/qt6.7. So perhaps updating your Flatpak runtimes already helps?

**Comment by celfred** [comment]
Wow… THANK YOU so much for such precise and quick feedback. It will require me to re-read all your indications and apply them little by little, but I'll keep you updated about it in a few days. I have a feeling I'll learn a LOT from what you wrote.
Thanks !

**Comment by celfred** [comment]
Ok, I'm back after having spent a couple of hours testing things and trying to understand (and apply) all your advice. I have improved (thanks again !) but I still have remarks / worries : 
- It seems like my Flatpak runtime is 6.7 and that must explain indeed the crash on the select. I have replaced my select by buttons for the moment as a workaround.
- I have removed all code related to OpenBoard interaction (the idea was to keep data over different days, but I'll see after my next point is solved).
- And here's the final worry : even with the core version (which I'll attach at the end of this post), everything works as expected BUT if I quit OpenBoard and come back, I still have a grey box and I can't see my widget any more. I would expect it to initialize again. And I just can't understand why. I have removed Jquery dependency, I have built the simplest thing I could think of, and I have commented out all that needs more work once I'll find this problem out).

The new zip archive : 
[challenge-light.wgt.zip](https://github.com/user-attachments/files/17212667/challenge-light.wgt.zip)

If you have a minute to point me in the right direction, I would greatly appreciate :)

**Comment by letsfindaway** [comment]
Unfortunately, my compatibility checker is just a string search engine. So it also detects the commented code. If you remove it, then the compatibility warning is no longer displayed.

I have not implemented a full fledged code parser for the compatibility check, but just a set of regular expressions. They also fire if the code is commented.

**Comment by sebojolais** [comment]
Hi, 

1.
I has tested the archive `challenge-light` app just now and I did not observe your last issue. When I reopen OB on the previous page, I can see your application without a gray rectangle. 
OB : `dev` branch
OS : Linux Ubuntu 22.04 (KDE Neon)
Qt : 5.15.6

2.
Because it seems your are from France, there is a [description](https://forge.apps.education.fr/openboard/applications/-/wikis/home/Comment-adapter-une-application-web-pour-l%E2%80%99int%C3%A9grer-%C3%A0-OpenBoard-%3F) of how to adapt Web app to OB that could be useful for your next steps. (but it is in french)

**Comment by celfred** [comment]
Well… I have deleted all my commented out lines and I still have the grey box when I come back to OB :cry: I have no idea what's going on…
@sebojolais Thanks for the link. It's very helpful (yes, I'm French). I'll start my widget from scratch apllying the advice given on your link.

Final remark : I'll also try and compare this Challenge widget to my Date widget which work fine…

I'll keep you updated if I find anything interesting about this.

Thanks again for your help.

**Comment by letsfindaway** [comment]
Attached my version where I removed all comments. It works for me.
[challenge.wgt.zip](https://github.com/user-attachments/files/17227612/challenge.wgt.zip)

**Comment by celfred** [comment]
Thanks ! And here's a new mystery to me. I did exactly the same and my version didn't work on relaunch but yours does (and I have compared files line by line). I have also restarted from scratch by copying my working Date widget and modifying the files (html, xml, js) and now it works.
So that's a good thing, but I have no clue of what the problem was :( Could it be some cache thing ? Really, I don't know.
I have worked on a version following @sebojolais recommendations and I have managed to make a workable (on y system !) version saving the number of groups and the number of challenges (i.e. the number of rows and columns of my table). Yeah, I know, it's not much, but beginners begin slow :)
My next step will be to find a way to save the validated challenges so I can reload them when restarting OB.

Here's the 'in-progress' working version : 
[FLChallenges.wgt.zip](https://github.com/user-attachments/files/17228873/FLChallenges.wgt.zip)

**Comment by celfred** [comment]
Me again,

Just as a follow-up and a final thanks the help, here's a working version with persisting state of all validated cells. My choice was to save the innerHTML of the table in a variable and read from it when loading.
It seems to work and I'm happy with it at the moment :)
