### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by multun** [OpenBoard-org/OpenBoard#330]
```
=================================================================
==27089==ERROR: AddressSanitizer: SEGV on unknown address 0x7f2572800393 (pc 0x7f25efb7b484 bp 0x7fff5a0b5060 sp 0x7fff5a0b4e40 T0)
==27089==The signal is caused by a READ memory access.
    #0 0x7f25efb7b483 in __dynamic_cast (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa9483)
    #1 0x560c52dc7673 in UBBoardController::ClearUndoStack() src/board/UBBoardController.cpp:1701
    #2 0x560c52dc91be in UBBoardController::closing() src/board/UBBoardController.cpp:1899
    #3 0x560c52e354d6 in UBApplication::closing() src/core/UBApplication.cpp:463
    #4 0x560c52e34fab in UBApplication::closeEvent(QCloseEvent*) src/core/UBApplication.cpp:449
    #5 0x560c533ee6ec in UBApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) build/linux/debug/moc/moc_UBApplication.cpp:124
    #6 0x7f25eff943f7 in QMetaObject::activate(QObject*, int, int, void**) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b13f7)
    #7 0x560c5341daeb in UBMainWindow::closeEvent_Signal(QCloseEvent*) build/linux/debug/moc/moc_UBMainWindow.cpp:143
    #8 0x560c5311e030 in UBMainWindow::closeEvent(QCloseEvent*) src/gui/UBMainWindow.cpp:151
    #9 0x7f25f0f7a04d in QWidget::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1ad04d)
    #10 0x7f25f108e827 in QMainWindow::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x2c1827)
    #11 0x7f25f0f37a85 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x16aa85)
    #12 0x7f25f0f40dff in QApplication::notify(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x173dff)
    #13 0x7f25eff68a29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x285a29)
    #14 0x7f25f0f75507 in QWidgetPrivate::close_helper(QWidgetPrivate::CloseMode) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1a8507)
    #15 0x7f25f0f95b51  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1c8b51)
    #16 0x7f25f0f99260  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1cc260)
    #17 0x7f25f0f37a85 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x16aa85)
    #18 0x7f25f0f40dff in QApplication::notify(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x173dff)
    #19 0x7f25eff68a29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x285a29)
    #20 0x7f25f07eecb4 in QGuiApplicationPrivate::processCloseEvent(QWindowSystemInterfacePrivate::CloseEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x123cb4)
    #21 0x7f25f07f3621 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x128621)
    #22 0x7f25f07cd754 in bool QWindowSystemInterfacePrivate::handleWindowSystemEvent<QWindowSystemInterface::SynchronousDelivery>(QWindowSystemInterfacePrivate::WindowSystemEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x102754)
    #23 0x7f25f07e0b1e in QPlatformWindow::close() (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x115b1e)
    #24 0x7f25e92b281d in ffi_call_unix64 (/lib/x86_64-linux-gnu/libffi.so.6+0x681d)
    #25 0x7f25e92b21ee in ffi_call (/lib/x86_64-linux-gnu/libffi.so.6+0x61ee)
    #26 0x7f25e3a94317  (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x9317)
    #27 0x7f25e3a90c47  (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x5c47)
    #28 0x7f25e3a9219b in wl_display_dispatch_queue_pending (/lib/x86_64-linux-gnu/libwayland-client.so.0+0x719b)
    #29 0x7f25e385dcc1 in QtWaylandClient::QWaylandDisplay::flushRequests() src/client/qwaylanddisplay.cpp:187
    #30 0x7f25eff943f7 in QMetaObject::activate(QObject*, int, int, void**) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b13f7)
    #31 0x7f25effa10c4 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2be0c4)
    #32 0x7f25effa1420 in QSocketNotifier::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2be420)
    #33 0x7f25f0f37a85 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x16aa85)
    #34 0x7f25f0f40dff in QApplication::notify(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x173dff)
    #35 0x7f25eff68a29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x285a29)
    #36 0x7f25effc1294  (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2de294)
    #37 0x7f25ee1398bc in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x518bc)
    #38 0x7f25ee139b3f  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51b3f)
    #39 0x7f25ee139be2 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51be2)
    #40 0x7f25effc0634 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2dd634)
    #41 0x7f25eff675ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2845ca)
    #42 0x7f25eff6f335 in QCoreApplication::exec() (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x28c335)
    #43 0x560c52e34646 in UBApplication::exec(QString const&) src/core/UBApplication.cpp:363
    #44 0x560c52e2f1bc in main src/core/main.cpp:133
    #45 0x7f25ef7631e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #46 0x560c52cd451d in _start (/home/victor/tools/OpenBoard/build/linux/debug/product/OpenBoard+0x1b651d)
```

**Comment by multun** [comment]
just got a very similar crash while adding a new page
```
==6145==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f78ca1374b8 bp 0x7ffe7116c8c0 sp 0x7ffe7116c6a0 T0)
==6145==The signal is caused by a READ memory access.
==6145==Hint: address points to the zero page.
    #0 0x7f78ca1374b7 in __dynamic_cast (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa94b7)
    #1 0x55fe01cf4673 in UBBoardController::ClearUndoStack() src/board/UBBoardController.cpp:1701
    #2 0x55fe01cf2a6c in UBBoardController::setActiveDocumentScene(UBDocumentProxy*, int, bool, bool) src/board/UBBoardController.cpp:1560
    #3 0x55fe01cf27f3 in UBBoardController::setActiveDocumentScene(int) src/board/UBBoardController.cpp:1536
    #4 0x55fe01cde9bc in UBBoardController::addScene() src/board/UBBoardController.cpp:524
    #5 0x55fe0230f09b in UBBoardController::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) build/linux/debug/moc/moc_UBBoardController.cpp:466
    #6 0x7f78ca5503f7 in QMetaObject::activate(QObject*, int, int, void**) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b13f7)
    #7 0x7f78cb4ed405 in QAction::triggered(bool) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x164405)
    #8 0x7f78cb4efac1 in QAction::activate(QAction::ActionEvent) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x166ac1)
    #9 0x55fe01d1d83a in QAction::trigger() /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:187
    #10 0x55fe01d12f5d in UBBoardPaletteManager::pagePaletteButtonReleased() src/board/UBBoardPaletteManager.cpp:351
    #11 0x55fe02316327 in UBBoardPaletteManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) build/linux/debug/moc/moc_UBBoardPaletteManager.cpp:209
    #12 0x7f78ca5503f7 in QMetaObject::activate(QObject*, int, int, void**) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2b13f7)
    #13 0x7f78cb5e8600  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x25f600)
    #14 0x7f78cb5e988e  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x26088e)
    #15 0x7f78cb5e9a64 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x260a64)
    #16 0x7f78cb6dc9ad in QToolButton::mouseReleaseEvent(QMouseEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x3539ad)
    #17 0x7f78cb53604d in QWidget::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1ad04d)
    #18 0x7f78cb6dca57 in QToolButton::event(QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x353a57)
    #19 0x7f78cb4f3a85 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x16aa85)
    #20 0x7f78cb4fd052 in QApplication::notify(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x174052)
    #21 0x7f78ca524a29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x285a29)
    #22 0x7f78cb4fc156 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x173156)
    #23 0x7f78cb55214c  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1c914c)
    #24 0x7f78cb554fdb  (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x1cbfdb)
    #25 0x7f78cb4f3a85 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x16aa85)
    #26 0x7f78cb4fcdff in QApplication::notify(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Widgets.so.5+0x173dff)
    #27 0x7f78ca524a29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x285a29)
    #28 0x7f78cadadd72 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x126d72)
    #29 0x7f78cadaf5fa in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x1285fa)
    #30 0x7f78cad8926a in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Gui.so.5+0x10226a)
    #31 0x7f78bde98903  (/lib/x86_64-linux-gnu/libQt5WaylandClient.so.5+0x90903)
    #32 0x7f78c86f58bc in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x518bc)
    #33 0x7f78c86f5b3f  (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51b3f)
    #34 0x7f78c86f5be2 in g_main_context_iteration (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x51be2)
    #35 0x7f78ca57c634 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2dd634)
    #36 0x7f78ca5235ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x2845ca)
    #37 0x7f78ca52b335 in QCoreApplication::exec() (/lib/x86_64-linux-gnu/libQt5Core.so.5+0x28c335)
    #38 0x55fe01d61646 in UBApplication::exec(QString const&) src/core/UBApplication.cpp:363
    #39 0x55fe01d5c1bc in main src/core/main.cpp:133
    #40 0x7f78c9d1f1e2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x271e2)
    #41 0x55fe01c0151d in _start (/home/victor/tools/OpenBoard/build/linux/debug/product/OpenBoard+0x1b651d)
```

**Comment by kaamui** [comment]
Helo,

yeah it's a known issue. You just need to use the eraser, then the "erase all" button, and you should have clearUndoStack trying to delete objects no longer existing (because the eraser selector implies you create new objects from the previous ones (minus the deleted area)
