### ISSUE TITLE
Crash when trying to open a specific web page

### ISSUE THREAD

**Issue by jose1711** [OpenBoard-org/OpenBoard#558]
Switched to "Web", trying to open http://www.dsl.sk/ resulted in SIGSEGV:
```
Thread 1 "openboard" received signal SIGSEGV, Segmentation fault.
0x00007fffccabf4d7 in gdk_display_open () from /usr/lib/libgdk-x11-2.0.so.0
(gdb) bt
#0  0x00007fffccabf4d7 in gdk_display_open () at /usr/lib/libgdk-x11-2.0.so.0
#1  0x00007fffcca8a542 in gdk_display_open_default_libgtk_only () at /usr/lib/libgdk-x11-2.0.so.0
#2  0x00007fff85fc08be in gtk_init () at /usr/lib/libgtk-x11-2.0.so.0
#3  0x00007ffff347eeca in  () at /usr/lib/libQt5WebKit.so.5
#4  0x00007ffff3476468 in  () at /usr/lib/libQt5WebKit.so.5
#5  0x00007ffff45b845e in WebCore::ScrollView::addChild(WTF::PassRefPtr<WebCore::Widget>) () at /usr/lib/libQt5WebKit.so.5
#6  0x00007ffff3eda499 in WebCore::WidgetHierarchyUpdatesSuspensionScope::moveWidgets() () at /usr/lib/libQt5WebKit.so.5
#7  0x00007ffff45429b5 in  () at /usr/lib/libQt5WebKit.so.5
#8  0x00007ffff45429ed in  () at /usr/lib/libQt5WebKit.so.5
#9  0x00007ffff41acf98 in WebCore::Document::updateLayoutIgnorePendingStylesheets(WebCore::Document::RunPostLayoutTasks) () at /usr/lib/libQt5WebKit.so.5
#10 0x00007ffff3ffd1a5 in  () at /usr/lib/libQt5WebKit.so.5
#11 0x00007ffff400b7a8 in WebCore::HTMLPlugInElement::pluginWidget(WebCore::HTMLPlugInElement::PluginLoadingPolicy) const () at /usr/lib/libQt5WebKit.so.5
#12 0x00007ffff42c7385 in  () at /usr/lib/libQt5WebKit.so.5
#13 0x00007ffff42d5562 in WebCore::pluginScriptObject(JSC::ExecState*, WebCore::JSHTMLElement*) () at /usr/lib/libQt5WebKit.so.5
#14 0x00007ffff42d5725 in  () at /usr/lib/libQt5WebKit.so.5
#15 0x00007ffff4d778b0 in  () at /usr/lib/libQt5WebKit.so.5
#16 0x00007ffff398f9c4 in  () at /usr/lib/libQt5WebKit.so.5
#17 0x00007ffff374db7e in  () at /usr/lib/libQt5WebKit.so.5
#18 0x00007fffcc5f8000 in  ()
#19 0x00007ffff372d7eb in  () at /usr/lib/libQt5WebKit.so.5
#20 0x0000000000000002 in  ()
#21 0x00007fffcf507500 in  ()
#22 0x00007fffffffb930 in  ()
#23 0x00007fffffffb8d0 in  ()
#24 0x00007ffff374ae8c in  () at /usr/lib/libQt5WebKit.so.5
#25 0x00007fff87975a80 in  ()
#26 0x00007fff87982980 in  ()
#27 0x0000001000000002 in  ()
#28 0x00007fff878a3c20 in  ()
#29 0x00007fff878a3540 in  ()
#30 0x000000000000000a in  ()
#31 0x00007fffcc5f8000 in  ()
#32 0x00007fffffffbfe0 in  ()
#33 0x00007fffffffc160 in  ()
#34 0x667d6a80b9c98900 in  ()
#35 0x00007fff879e2940 in  ()
#36 0x00007ffff36f24d6 in  () at /usr/lib/libQt5WebKit.so.5
#37 0x00007ffff36c6abf in  () at /usr/lib/libQt5WebKit.so.5
#38 0x00007ffff34986e7 in JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) () at /usr/lib/libQt5WebKit.so.5
#39 0x00007ffff34986fa in JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) ()
    at /usr/lib/libQt5WebKit.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#40 0x00007ffff43007d7 in  () at /usr/lib/libQt5WebKit.so.5
#41 0x00007ffff416f04b in  () at /usr/lib/libQt5WebKit.so.5
#42 0x00007ffff416f472 in  () at /usr/lib/libQt5WebKit.so.5
#43 0x00007ffff4188139 in  () at /usr/lib/libQt5WebKit.so.5
#44 0x00007ffff41888e7 in  () at /usr/lib/libQt5WebKit.so.5
#45 0x00007ffff419c9f3 in  () at /usr/lib/libQt5WebKit.so.5
#46 0x00007ffff41b5d11 in WebCore::ContainerNode::appendChild(WTF::Ref<WebCore::Node>&&, int&) () at /usr/lib/libQt5WebKit.so.5
#47 0x00007ffff41b6994 in WebCore::Node::appendChild(WTF::PassRefPtr<WebCore::Node>, int&) () at /usr/lib/libQt5WebKit.so.5
#48 0x00007ffff42d52eb in WebCore::JSNode::appendChild(JSC::ExecState&) () at /usr/lib/libQt5WebKit.so.5
#49 0x00007ffff488bfc9 in  () at /usr/lib/libQt5WebKit.so.5
#50 0x00007fff87fff0c8 in  ()
#51 0x00007fffffffc070 in  ()
#52 0x00007ffff3750d80 in  () at /usr/lib/libQt5WebKit.so.5
#53 0x0000000000000000 in  ()
(gdb) 
```

Arch Linux x86_64, OpenBoard built from master

**Comment by letsfindaway** [comment]
From your stack trace you see, that the crash occurs deeply in QWebKit, or even much below in gdk (see https://en.wikipedia.org/wiki/GDK). It is unlikely that OpenBoard can help here. Does this only occur on specific web pages or in general? Please note that QWebKit is deprecated since years. It is still used by OpenBoard 1.6.x, but work is underway to move to QWebEngine (see branch 1.7-dev).

As you're probably building OpenBoard by your own you could try to build a version based on this branch plus the patches provided in #545. You can retrieve the patch corresponding to this pull request from Github at https://github.com/OpenBoard-org/OpenBoard/pull/545.patch.

This version removes QWebKit as dependency and instead adds QWebEngine and QWebEngineWidgets and might probably fix your problem. Note however that these are still development branches and not released.

**Comment by jose1711** [comment]
> Does this only occur on specific web pages or in general?

On specific web pages only.

> This version removes QWebKit as dependency and instead adds QWebEngine and QWebEngineWidgets and might probably fix your problem. Note however that these are still development branches and not released.

Thank you, will test if when I have a moment.
